### ISSUE TITLE
Armbian Difference between cli and cli minimal package

### ISSUE THREAD

**Issue by zounp** [igorpecovnik/igorpecovnik#1]
Hello Igor,

Thanks for your work on Armbian.
On https://www.armbian.com/faq/what-is-missing-in-minimal-diet-image/ could you be more explicit on the differences beween cli and cli minimal images.
And, the links form 
    Debian Bullseye
    Ubuntu Jammy
do yield an empty page where I expect content. Maybe some more information on the differences.

Thanks

**Comment by igorpecovnik** [comment]
> do yield an empty page where I expect content. 

It looks like that content was removed when pastebin service was upgraded. Sadly I don't know which issues to fix first. My family problems or those which "customers" reported and are waiting for attention already several years
- https://forum.armbian.com/forum/38-feature-requests/
- https://github.com/armbian/build/issues

or this very urgent matter that was pinned to a personal Git profile?

> could you be more explicit on the differences beween cli and cli minimal images.

With all respect, but this is something you can do without damaging my time. Download both images and diff the package base and eventually report so others can perhaps use this info.
